### ISSUE TITLE
Why divide the std of activations only during training, while not in the inference mode?

### ISSUE THREAD

**Issue by talenz** [z-hXu/ReCU#6]
It seems like a little unreasonable to me, since the training and inference are not consistent for doing so.

Is there any special considerations or does it improve the performance?

Thanks for the nice implementations~

**Comment by z-hXu** [comment]
It's still consistent because the std of activations is always positive, sign(a) and sign(a/std_a) are equivalent. 
We hope to improve the performance by dividing the std of activations, but the calculation for std of activations during inference is expensive, so we use this way to avoid the extra computation during inference and obtain the gain during training.

**Comment by talenz** [comment]
> It's still consistent because the std of activations is always positive, sign(a) and sign(a/std_a) are equivalent. We hope to improve the performance by dividing the std of activations, but the calculation for std of activations during inference is expensive, so we use this way to avoid the extra computation during inference and obtain the gain during training.

Ok, now I understand the consistency because of the sign. Another question, how does the division of std boost the performance? Or what's the motivation behind this? 

Thanks for the reply
`

**Comment by z-hXu** [comment]
It's equivalent to adaptive learning rate scaling. 
We find the convergence speed of each layer of the network is quite different, and this method can solve this problem.
